// 素材库
export const mockMaterials = [
  {
    id: 'm1',
    title: '极简UI设计素材包',
    author: '设计小站',
    type: 'UI/UX',
    resourceType: 'material' as const,
    imageUrl: '/images/material/ui_kit.png',
    description: '包含多种UI设计元素和组件，适用于移动端和网页设计',
    tags: ['UI', '设计', '组件', '现代'],
    fileSize: '2.5MB',
    authorAvatar: '/images/avatar/designer1.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm2',
    title: '水彩画笔刷套装',
    author: '水彩君',
    type: '插画',
    resourceType: 'material' as const,
    imageUrl: '/images/material/watercolor_brush.jpg',
    description: '20款自然水彩笔刷，适合Procreate和PS，模拟真实水彩晕染效果',
    tags: ['笔刷', '水彩', 'Procreate', '插画'],
    fileSize: '4.8MB',
    authorAvatar: '/images/avatar/watercolorist.png',
    dimension: '2048x2048',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm3',
    title: '科幻城市3D模型包',
    author: 'CG天堂',
    type: '游戏',
    resourceType: 'material' as const,
    imageUrl: '/images/material/sci_fi_city.png',
    description: '未来感建筑、飞行器、霓虹灯等科幻元素，适配Blender和Maya',
    tags: ['3D', '科幻', '城市', '游戏'],
    fileSize: '128MB',
    authorAvatar: '/images/avatar/cg_heaven.png',
    dimension: '多尺寸',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm4',
    title: '日系动漫角色线稿集',
    author: '漫画家小宇',
    type: '动漫',
    resourceType: 'material' as const,
    imageUrl: '/images/material/anime_sketch.jpg',
    description: '包含50+高质量角色线稿，可用于上色练习或创作参考',
    tags: ['动漫', '线稿', '角色', '参考'],
    fileSize: '15.3MB',
    authorAvatar: '/images/avatar/mangaka.png',
    dimension: 'A4',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm5',
    title: '复古平面纹理包',
    author: '复古工坊',
    type: '平面',
    resourceType: 'material' as const,
    imageUrl: '/images/material/vintage_texture.jpg',
    description: '纸张、划痕、印刷网点等复古质感纹理，PSD格式',
    tags: ['纹理', '复古', '平面', 'PSD'],
    fileSize: '8.2MB',
    authorAvatar: '/images/avatar/vintage.png',
    dimension: '4000x4000',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm6',
    title: '概念设计参考图集：废墟',
    author: '概念艺术家联盟',
    type: '建筑',
    resourceType: 'material' as const,
    imageUrl: '/images/material/ruins_ref.jpg',
    description: '100+张高质量废墟场景参考图，涵盖不同风格和角度',
    tags: ['概念设计', '场景', '废墟', '参考'],
    fileSize: '256MB',
    authorAvatar: '/images/avatar/concept_union.png',
    dimension: '多种',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm7',
    title: '服装褶皱笔刷',
    author: '画衣小助手',
    type: '服装',
    resourceType: 'material' as const,
    imageUrl: '/images/material/clothing_brush.jpg',
    description: '专门用于绘制服装褶皱的笔刷集，包含布料、丝绸、牛仔等质感',
    tags: ['笔刷', '服装', '褶皱', '布料'],
    fileSize: '3.2MB',
    authorAvatar: '/images/avatar/clothing.png',
    dimension: '2048x2048',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm8',
    title: '汽车设计线稿模板',
    author: '工业设计库',
    type: '汽车',
    resourceType: 'material' as const,
    imageUrl: '/images/material/car_template.jpg',
    description: '多角度汽车线稿模板，适合设计师快速勾勒造型',
    tags: ['汽车', '线稿', '设计', '模板'],
    fileSize: '5.5MB',
    authorAvatar: '/images/avatar/industrial.png',
    dimension: '3000x2000',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm9',
    title: '野生动物高清照片素材',
    author: '自然摄影师',
    type: '动物',
    resourceType: 'material' as const,
    imageUrl: '/images/material/wildlife.jpg',
    description: '200+野生动物高清摄影图，可用于绘画参考和背景合成',
    tags: ['动物', '摄影', '参考', '高清'],
    fileSize: '450MB',
    authorAvatar: '/images/avatar/nature.png',
    dimension: '4K',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 'm10',
    title: '赛博朋克霓虹色盘',
    author: '配色实验室',
    type: '插画',
    resourceType: 'material' as const,
    imageUrl: '/images/material/cyber_palette.png',
    description: '30种赛博朋克风格配色方案，包含色值和应用示例',
    tags: ['配色', '赛博朋克', '色盘', '插画'],
    fileSize: '1.2MB',
    authorAvatar: '/images/avatar/color_lab.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
];

// 教程库
export const mockTutorials = [
  {
    id: 't1',
    title: '速写基础：快速捕捉动态',
    author: '速写达人',
    type: '速写',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/gesture_drawing.jpg',
    description: '30分钟视频课程，讲解如何用线条表现人物动态，适合初学者',
    tags: ['速写', '动态', '基础', '视频'],
    fileSize: '320MB',
    authorAvatar: '/images/avatar/sketch_master.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't2',
    title: '人体结构精讲：躯干',
    author: '人体解剖研究所',
    type: '人体',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/torso_anatomy.jpg',
    description: '详细讲解躯干骨骼和肌肉结构，附赠练习图集',
    tags: ['人体', '解剖', '结构', '进阶'],
    fileSize: '850MB',
    authorAvatar: '/images/avatar/anatomy.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't3',
    title: '动态捕捉技巧：战斗场景',
    author: '动作大师',
    type: '动态',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/action_pose.jpg',
    description: '如何绘制充满张力的战斗动作，分析经典作品案例',
    tags: ['动态', '动作', '战斗', '插画'],
    fileSize: '480MB',
    authorAvatar: '/images/avatar/action_master.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't4',
    title: '色彩理论进阶：光影与情绪',
    author: '色彩魔法师',
    type: '色彩',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/color_emotion.jpg',
    description: '深入讲解色彩如何影响画面情绪，实战演练冷暖对比',
    tags: ['色彩', '光影', '情绪', '进阶'],
    fileSize: '620MB',
    authorAvatar: '/images/avatar/color_mage.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't5',
    title: '设计思维：从草图到成品',
    author: '设计学院',
    type: '设计',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/design_process.jpg',
    description: '完整的设计流程演示，包括调研、草图、渲染和展示',
    tags: ['设计', '流程', '思维', '案例'],
    fileSize: '1.2GB',
    authorAvatar: '/images/avatar/design_school.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't6',
    title: '氛围感营造：夜景绘制',
    author: '场景插画师',
    type: '氛围感',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/night_scene.jpg',
    description: '教你用光影和颜色打造梦幻夜景，包含笔刷技巧',
    tags: ['氛围感', '夜景', '光影', '场景'],
    fileSize: '550MB',
    authorAvatar: '/images/avatar/scene_artist.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't7',
    title: '大场景构图法则',
    author: '场景大师',
    type: '大场景',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/large_landscape.jpg',
    description: '如何布局宏大场景，利用透视和层次引导视线',
    tags: ['构图', '大场景', '透视', '层次'],
    fileSize: '430MB',
    authorAvatar: '/images/avatar/landscape_master.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't8',
    title: '水墨风格插画教程',
    author: '国风画师',
    type: '插画',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/ink_art.jpg',
    description: '传统水墨与现代插画结合，讲解笔法、墨色和意境',
    tags: ['国风', '水墨', '插画', '传统'],
    fileSize: '680MB',
    authorAvatar: '/images/avatar/guofeng.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't9',
    title: '游戏原画设计：怪物篇',
    author: '游戏原画师联盟',
    type: '游戏',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/monster_design.jpg',
    description: '从概念到设计，打造独特怪物造型，含步骤图',
    tags: ['游戏', '原画', '怪物设计', '概念'],
    fileSize: '920MB',
    authorAvatar: '/images/avatar/game_art_union.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't10',
    title: '建筑速写入门',
    author: '建筑绘',
    type: '建筑',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/architecture_sketch.jpg',
    description: '快速记录建筑特征，掌握透视和线条表现',
    tags: ['建筑', '速写', '透视', '入门'],
    fileSize: '380MB',
    authorAvatar: '/images/avatar/arch_sketch.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't11',
    title: '服装设计效果图教程',
    author: '服装设计工坊',
    type: '服装',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/fashion_illustration.jpg',
    description: '手绘服装效果图技巧，包括褶皱、材质和动态展示',
    tags: ['服装', '效果图', '褶皱', '设计'],
    fileSize: '560MB',
    authorAvatar: '/images/avatar/fashion_workshop.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
  {
    id: 't12',
    title: '汽车渲染技法：Keyshot篇',
    author: '工业渲染师',
    type: '汽车',
    resourceType: 'tutorial' as const,
    imageUrl: '/images/tutorial/car_rendering.jpg',
    description: '使用Keyshot软件对汽车模型进行写实渲染，材质和灯光设置',
    tags: ['汽车', '渲染', 'Keyshot', '工业设计'],
    fileSize: '750MB',
    authorAvatar: '/images/avatar/industrial_render.png',
    dimension: '1920x1080',
    isFollowing: false,
    isCollected: false,
  },
];